### PR TITLE
Use engine 0.2

### LINKED ISSUE #22: Flaky tests: Dataframe containing duplicated files is not properly saved
## Problem

tests sometimes fail with the following output.

## How to reproduce

Run `./sbt test` many times, and it'll fail sometimes. It is difficult to reproduce in the CI (because it takes more time), but I could see there that error a couple of times.

Using the tip of [dpordomingo/gemini::reproduce-issue-22](https://github.com/dpordomingo/gemini/tree/reproduce-issue-22), I created a gist with the 3 scenarios I found:

### Test succeeds
No data is stored in the `test_hashes_duplicates`
- [`report1-succeeding.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt) -> output of the passing tests 
- [`report1-succeeding-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-db-txt) -> content of the testing keyspaces. Both keyspaces are full of data

### Test fails
No data at all is stored in the `test_hashes_duplicates`
- [`report2-failing.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-txt) -> output of the failing test
- [`report2-failing-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-db-txt) -> content of the testing keyspaces. There is *no data* in `test_hashes_duplicates`

Partial data is stored in the `test_hashes_duplicates`
- [`report3-failing.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt) -> output of the failing test
- [`report3-failing-db.txt`](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-db-txt) -> content of the testing keyspaces. Only the half of the data retrieved by engine were saved in `test_hashes_duplicates` (the `srcd/borges` repo is hashed, but `erizocosmico/borges` repo is lost.

## More info

It requires more investigation, but it could be related when how data is stored during the tests before the test cases start running.

Currently, in the `beforeAll` section, it is created two keyspaces (`test_hashes_duplicates` for tests needing duplicates, `test_hashes_uniques` for tests needing no duplicates)
This is done in two stages:
1. engine returns a `DataFrame` containing all the files in the given siva files,
2. the `DataFrame` is stored in Cassandra <-- (I think something fails at this point) 

After the `beforeAll` the test cases run, and (sometimes) the ones asserting that there are duplicate files in `test_hashes_duplicates` fails.

It can be seen in the logs, that in all situations the `DataFrame` is populated with the right contents ([1](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L252),[2](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report2-failing-txt-L252),[3](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt-L252)).
But then:
- when no data is stored at all, at the `save` stage, there is always outputed `Wrote 0 rows to test_hashes_duplicates.blob_hash_files`
- when half of the data is stored, at the `save` stage, there is one row that says:  `Wrote 47 rows to test_hashes_duplicates.blob_hash_files` [47 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-txt-L288)
- when everything go well, at the `save` stage, there are some rows that say `Wrote n rows to test_hashes_duplicates.blob_hash_files`, and the sum of all rows sum `80` [33 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L272) +  [47 rows](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report1-succeeding-txt-L276)

## Hints

- Why when duplicate data is partially saved into `test_hashes_duplicates`, the missing files are from `github.com/erizocosmico/borges.git`? ([here](https://gist.github.com/dpordomingo/1bb295d3ef4f36ded37ff9d9828ff865#file-report3-failing-db-txt))
- Why `DataFrame` is always populated with right data, but sometimes its data is not properly saved?

### PR DESCRIPTION
**Pull request by smacker**
fix #22

It should fix the problem with flaky tests.

### CODE REVIEW

File: src/main/scala/tech/sourced/gemini/Gemini.scala [hunk 1]
```diff
@@ -36,21 +36,17 @@ class Gemini(session: SparkSession, keyspace: String = Gemini.defautKeyspace) {
   }
 
   def hashForRepos(repos: DataFrame): DataFrame = {
```
Comment (dpordomingo) [inline src/main/scala/tech/sourced/gemini/Gemini.scala]: I think that now you removed the assignation you can also remove the `{` and `}` .

**Comment by smacker** [comment]
@dpordomingo I added detailed comments in the issue about what I have tried, results and so on. Please take a look there. Thanks!

File: src/main/scala/tech/sourced/gemini/Gemini.scala (hunk 1 above)
Comment (smacker) [reply src/main/scala/tech/sourced/gemini/Gemini.scala]: you are absolutely right or how people say in Vietnam "Đúng rồi"!
Cảm ơn nha! Fixed.

**Comment by dpordomingo** [comment]
Oh, great, the first one :)

**Comment by dpordomingo** [comment]
This PR also fixes #22
